### ISSUE TITLE
Crash on iso-10303 `action_schema/action_schema.exp` when using `expressir-2.1.0`

### ISSUE THREAD

**Issue by kwkwan** [lutaml/expressir#164]
When I ran:
```
require "expressir"
Expressir::Express::Parser.from_file("/path/to/iso-10303/schemas/resources/action_schema/action_schema.exp")
```

I got an error:
```
~/.rbenv/versions/3.1.5/lib/ruby/gems/3.1.0/gems/parslet-2.0.0/lib/parslet/cause.rb:70:in `raise': Failed to match sequence (spaces:SPACES schemaDecl:(SCHEMADECL{1, }) trailer:SPACES) at line 31 char 1. (Parslet::ParseFailed)
from ~/.rbenv/versions/3.1.5/lib/ruby/gems/3.1.0/gems/parslet-2.0.0/lib/parslet/atoms/base.rb:49:in `parse'
from ~/.rbenv/versions/3.1.5/lib/ruby/gems/3.1.0/gems/expressir-2.1.0/lib/expressir/express/parser.rb:305:in `from_file'
from (irb):2:in `<main>'
from ~/.rbenv/versions/3.1.5/lib/ruby/gems/3.1.0/gems/irb-1.4.1/exe/irb:11:in `<top (required)>'
from ~/.rbenv/versions/3.1.5/bin/irb:25:in `load'
from ~/.rbenv/versions/3.1.5/bin/irb:25:in `<top (required)>'
from ~/.rbenv/versions/3.1.5/lib/ruby/gems/3.1.0/gems/bundler-2.4.21/lib/bundler/cli/exec.rb:58:in `load'
from ~/.rbenv/versions/3.1.5/lib/ruby/gems/3.1.0/gems/bundler-2.4.21/lib/bundler/cli/exec.rb:58:in `kernel_load'
from ~/.rbenv/versions/3.1.5/lib/ruby/gems/3.1.0/gems/bundler-2.4.21/lib/bundler/cli/exec.rb:23:in `run'
from ~/.rbenv/versions/3.1.5/lib/ruby/gems/3.1.0/gems/bundler-2.4.21/lib/bundler/cli.rb:492:in `exec'
from ~/.rbenv/versions/3.1.5/lib/ruby/gems/3.1.0/gems/bundler-2.4.21/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
from ~/.rbenv/versions/3.1.5/lib/ruby/gems/3.1.0/gems/bundler-2.4.21/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
from ~/.rbenv/versions/3.1.5/lib/ruby/gems/3.1.0/gems/bundler-2.4.21/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
from ~/.rbenv/versions/3.1.5/lib/ruby/gems/3.1.0/gems/bundler-2.4.21/lib/bundler/cli.rb:34:in `dispatch'
from ~/.rbenv/versions/3.1.5/lib/ruby/gems/3.1.0/gems/bundler-2.4.21/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
from ~/.rbenv/versions/3.1.5/lib/ruby/gems/3.1.0/gems/bundler-2.4.21/lib/bundler/cli.rb:28:in `start'
... 5 levels...
```

The file is located at https://github.com/metanorma/iso-10303/blob/main/schemas/resources/action_schema/action_schema.exp

P.S.  `Expressir::Express::Parser.from_file` runs successfully when using expressir v1.4.x.

**Comment by epiccode-au** [comment]
The provided link is reporting as "not found".
Please attach the affected file as a separate file to this issue.

**Comment by kwkwan** [comment]
[action_schema.exp.zip](https://github.com/user-attachments/files/17895733/action_schema.exp.zip)

Please find the attached file for this issue.  Thank you.

**Comment by kwkwan** [comment]
Hi @epiccode-au @ronaldtse will assign you the proper permission to access the reported file.

**Comment by ronaldtse** [comment]
@epiccode-au you have access to the file.

**Comment by epiccode-au** [comment]
I still don't have access to the file.  I am still getting a 404 for https://github.com/metanorma/iso-10303/blob/main/schemas/resources/action_schema/action_schema.exp

**Comment by ronaldtse** [comment]
@epiccode-au do you have access now? I see you have accepted the invitation to the Metanorma organization which provides you with access to that particular file.

**Comment by ronaldtse** [comment]
@epiccode-au we do need to run Expressir on the full set of schemas under https://github.com/metanorma/iso-10303/tree/main/schemas:

* business_object_models/*/*.exp
* resources/*/*.exp
* modules/*/*.exp

**Comment by kwkwan** [comment]
Hi @epiccode-au Similar crash has been found in other resources in `iso-10303`.

Example:

```
[suma] Save plain schema: plain_schemas/resources/geometry_schema/geometry_schema.exp
[suma] [ERROR] Error occurred during processing. See details below.
[suma] Failed to match sequence (spaces:SPACES schemaDecl:(SCHEMADECL{1, }) trailer:SPACES) at line 30 char 1.
[suma] #<Parslet::ParseFailed: Failed to match sequence (spaces:SPACES schemaDecl:(SCHEMADECL{1, }) trailer:SPACES) at line 30 char 1.>
[suma] ~/.rbenv/versions/3.1.5/lib/ruby/gems/3.1.0/gems/parslet-2.0.0/lib/parslet/cause.rb:70:in `raise'
~/.rbenv/versions/3.1.5/lib/ruby/gems/3.1.0/gems/parslet-2.0.0/lib/parslet/atoms/base.rb:49:in `parse'
~/.rbenv/versions/3.1.5/lib/ruby/gems/3.1.0/gems/expressir-2.1.2/lib/expressir/express/parser.rb:429:in `from_file'
~/src/metanorma/suma/lib/suma/express_schema.rb:31:in `parsed'
~/src/metanorma/suma/lib/suma/express_schema.rb:38:in `to_plain'
~/src/metanorma/suma/lib/suma/express_schema.rb:53:in `block in save_exp'
~/src/metanorma/suma/lib/suma/express_schema.rb:52:in `open'
~/src/metanorma/suma/lib/suma/express_schema.rb:52:in `save_exp'
...
```

**Comment by kwkwan** [comment]
Closed as completed via https://github.com/lutaml/expressir/pull/213 and https://github.com/lutaml/expressir/pull/214.
